version: '3'

services:
  api:
    image: radoslawlandowski/blue_holidays_0.0.1
    restart: always
    ports:
      - 8014:8082
    environment:
      - BH_APP_CAL_API_KEY=${BH_APP_CAL_API_KEY}
      - BH_APP_PORT=8082